from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import MealCategoriesView

from .views import (
    SendOTPView,
    VerifyOTPView,
    MeView,
    LogoutView,
    OnboardingOptionsView,
    OnboardingCompleteView,
    OnboardingProfileView,
    DashboardTodayView,
    DashboardWeeklyView,
    DashboardMonthlyView,
    MealCategoriesView,
    MealRecommendationsView,
    AddMealEntryView,
    RemoveMealEntryView,
    ToggleMealEatenView,
    ProfileOverviewView,
    ProfileImageUploadView,
    ProfileSettingsView,
    HelpSupportView,
    DeleteAccountView,
)
from .views import DayMealsView, WeeklyMacrosView, CaloriesTrendView
urlpatterns = [
    path('auth/send-otp/', SendOTPView.as_view(), name='send-otp'),
    path('auth/verify-otp/', VerifyOTPView.as_view(), name='verify-otp'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('auth/logout/', LogoutView.as_view(), name='logout'),
    path('auth/me/', MeView.as_view(), name='me'),
    path('onboarding/options/', OnboardingOptionsView.as_view(), name='onboarding-options'),
    path('onboarding/complete/', OnboardingCompleteView.as_view(), name='onboarding-complete'),
    path('onboarding/profile/', OnboardingProfileView.as_view(), name='onboarding-profile'),
    path('dashboard/today/', DashboardTodayView.as_view(), name='dashboard-today'),
    path('dashboard/weekly/', DashboardWeeklyView.as_view(), name='dashboard-weekly'),
    path('dashboard/monthly/', DashboardMonthlyView.as_view(), name='dashboard-monthly'),
    path('meal/categories/', MealCategoriesView.as_view(), name='meal-categories'),
    path('meal/recommendations/', MealRecommendationsView.as_view(), name='meal-recommendations'),
    path('meal/add/', AddMealEntryView.as_view(), name='add-meal-entry'),
    path('meal/remove/<int:entry_id>/', RemoveMealEntryView.as_view(), name='remove-meal-entry'),
    path('meal/toggle-eaten/<int:entry_id>/', ToggleMealEatenView.as_view(), name='toggle-meal-eaten'),
    path('meal/day/', DayMealsView.as_view(), name='meal-day'),
    path('progress/weekly-macros/', WeeklyMacrosView.as_view(), name='weekly-macros'),
    path('progress/calories/', CaloriesTrendView.as_view(), name='calories-trend'),
    path('profile/overview/', ProfileOverviewView.as_view(), name='profile-overview'),
    path('profile/image-upload/', ProfileImageUploadView.as_view(), name='profile-image-upload'),
    path('profile/settings/', ProfileSettingsView.as_view(), name='profile-settings'),
    path('profile/update-settings/', ProfileSettingsView.as_view(), name='profile-update-settings'),
    path('profile/help/', HelpSupportView.as_view(), name='profile-help'),
    path('profile/delete-account/', DeleteAccountView.as_view(), name='delete-account'),
]
