# Generated by Django 4.2.1 on 2025-12-01 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serving', models.CharField(blank=True, max_length=100)),
                ('calories', models.FloatField(default=0)),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fats_g', models.FloatField(default=0)),
                ('diet_type', models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Vegan', 'Vegan'), ('Eggetarian', 'Eggetarian'), ('Keto / Low-Carb', 'Keto / Low-Carb'), ('High Protein', 'High Protein')], max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mealentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mealentry',
            name='serving',
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='carbs_g',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='fats_g',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='protein_g',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.food'),
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
