# Generated by Django 4.2.1 on 2025-12-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_food_remove_mealentry_name_remove_mealentry_serving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealentry',
            name='name',
            field=models.CharField(default='Unknown food', max_length=200),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='serving',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
