# Generated by Django 4.2.1 on 2025-12-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_profile_image_userappsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='mobile',
        ),
    ]
