# Generated by Django 4.2.1 on 2025-12-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_loginhistory_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynutritionsummary',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='mobile',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userappsettings',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
