# Generated by Django 4.2.1 on 2026-01-28 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_dailynutritionsummary_user_name_loginhistory_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Evening Snacks', 'Evening Snacks'), ('Dinner', 'Dinner')], max_length=20)),
                ('items_json', models.JSONField(blank=True, default=list)),
                ('goal', models.CharField(blank=True, max_length=50)),
                ('diet_preference', models.CharField(blank=True, max_length=50)),
                ('health_conditions', models.JSONField(blank=True, default=list)),
                ('target_calories', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date', 'meal_type')},
            },
        ),
    ]
