# Generated by Django 4.2.1 on 2026-01-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_allergies_userprofile_allergy_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynutritionsummary',
            name='carbs_target',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailynutritionsummary',
            name='fats_target',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailynutritionsummary',
            name='protein_target',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='eaten',
            field=models.BooleanField(default=False),
        ),
    ]
