# Generated by Django 4.2.1 on 2026-02-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_dailynutritionsummary_carbs_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mealrecommendation',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mealrecommendation',
            name='allergy_notes',
            field=models.TextField(blank=True),
        ),
    ]
