# Generated by Django 4.2.1 on 2026-02-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_food_allergies_mealrecommendation_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='mealrecommendation',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='mealrecommendation',
            name='allergy_notes',
        ),
    ]
