# Generated by Django 4.2.1 on 2026-02-24 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_food_allergies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailynutritionsummary',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Nutrition Summary', 'verbose_name_plural': 'Daily Nutrition Summaries'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('Sedentary', 'Sedentary (little or no exercise)'), ('Lightly Active', 'Lightly Active (light exercise/sports 1-3 days/week)'), ('Moderately Active', 'Moderately Active (moderate exercise/sports 3-5 days/week)'), ('Very Active', 'Very Active (hard exercise/sports 6-7 days a week)'), ('Extra Active', 'Extra Active (very hard exercise/physical job & training 2x/day)')], default='Sedentary', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Weight Tracking',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('exercise_name', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('calories_burned', models.FloatField(default=0)),
                ('intensity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Exercise Logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount_ml', models.PositiveIntegerField(default=0)),
                ('glasses', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Water Tracking',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
