# Generated by Django 4.2.1 on 2026-02-24 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_usernotification_sleeplog_medicinelog_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMealRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=100)),
                ('week_start_date', models.DateField()),
                ('recommendations_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Weekly Recommendations',
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medicinelog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sleeplog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='waterlog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='waterlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weightlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mealentry',
            name='food',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='activity_level',
        ),
        migrations.DeleteModel(
            name='ExerciseLog',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='MedicineLog',
        ),
        migrations.DeleteModel(
            name='SleepLog',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
        migrations.DeleteModel(
            name='WaterLog',
        ),
        migrations.DeleteModel(
            name='WeightLog',
        ),
    ]
