# Generated by Django 4.2.1 on 2026-02-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_weeklymealrecommendation_remove_feedback_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'verbose_name': 'Login History', 'verbose_name_plural': 'Login History'},
        ),
        migrations.AlterModelOptions(
            name='mealentry',
            options={'verbose_name': 'Meal Entry', 'verbose_name_plural': 'Meal Entries'},
        ),
        migrations.AlterModelOptions(
            name='mealrecommendation',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Recommendation', 'verbose_name_plural': 'Daily Recommendations'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User / Admin', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
