# Generated by Django 6.0.3 on 2026-04-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_food_alter_loginhistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Help & Support',
                'verbose_name_plural': 'Help & Support Queries',
            },
        ),
    ]
